### ISSUE TITLE
Doctype for HTML5 is stripped while using *-page.js

### ISSUE THREAD

**Issue by yutotakano** [mathjax/MathJax-demos-node#22]
MathJax@3 is awesome and I love how easy it has become to render MathJax server-side. I noticed one concerning bug for the script on this repo though, which is that upon using the `direct/tex2chtml-page` script for processing my HTML pages, the `<!DOCTYPE html>` is stripped away. Nothing has been changed in the script compared to the one available on this repo.

This broke several things that were reliant on the HTML5 specification to be declared, notably [tippy.js](https://atomiks.github.io/tippyjs/) and some layout tags. 

I am not asking for a feature to automatically add the Doctype string - that should be done before running it through MathJax. However, stripping it away sounds like something that requires some attention. If it is a simple configuration change, it would be nice to see the examples fixed, as I could not find documentation on this behaviour anywhere. 

|Screenshots|
|--|
|Before running `direct/tex2chtml-page`<br>![Before](https://i.imgur.com/UJ1xAmG.png)| 
|After running it<br>![After](https://i.imgur.com/6S8tf3H.png)|

(it also added MathJax CSS styles despite having 0 LaTeX code on this page, but that's irrelevant to this)

**Comment by yutotakano** [comment]
> First, you can modify the program to insert whatever DOCTYPE you need, so you shield be able to get the output you want that way.

I thought about that as a quick solution, but I was concerned that if a DOCTYPE is removed, maybe some other part of the HTML is removed too, which might require attention. Thankfully it seems like it's only this.

 > Second, version 3.1 is coming out next week, [...] so in a week, this will be fixed

Thank you very much! I can't wait!

> Your suggestion to not include the stylesheet if there is no math is a good one.

Right, I included it in parenthesis because it isn't related to the doctype issue, but I wasn't sure where else it should be posted. Hopefully it is implemented.

**Comment by yutotakano** [comment]
I've seen the commits merged to master and the MathJax source bumped to 3.1.0 - I'm more than thrilled! Closing this issue as resolved now.

**Comment by dpvc** [comment]
I also implemented the removal of the stylesheet if there is no math in the document.  The new versions of the node examples are available here, and you should be able to use them now (you will need to `npm install` again to update the dependencies).
