### ISSUE TITLE
Pound symbol is italic by default.

### ISSUE THREAD

**Issue by senthilsam** [mathjax/MathJax-demos-node#24]
Hi I used to convert the below mathml equation using direct/mml2svg, the pound symbol is coming as italic by default. whereas i haven't specified any formatting here.

```
<mml:math><mml:mrow><mml:mtext>&#x0024;</mml:mtext><mml:mn>1.60</mml:mn><mml:mo>/</mml:mo><mml:mtext>&#x00A3;</mml:mtext></mml:mrow></mml:math>
```

output:
![image](https://user-images.githubusercontent.com/4089212/95833612-80dab780-0d59-11eb-802d-18d208ba9fc5.png)

Please someone let me know how to solve this?

**Comment by dpvc** [comment]
The MathJax TeX fonts, which were derived from from Computer Modern Fonts, don't include an upright pound symbol, only the italic one.  So you would have to specify a different font in order to get an upright one.  For example, you could use

```
<mtext style="font-family:Times">&#xA3;</mtext>
```

for that.

**Comment by senthilsam** [comment]
Thank You
