### ISSUE TITLE
Is it faster than MathJax-node?

### ISSUE THREAD

**Issue by fivecakes** [mathjax/MathJax-demos-node#28]
Is it faster than [MathJax-node](https://github.com/mathjax/MathJax-node)?

**Comment by dpvc** [comment]
Yes.  Aside from version 3 being 60 to 80% faster than version 2 in general, mathjax-node needed to use the jsdom library to implement a browser DOM in node, and jsdom is relatively slow.  MathJax v3 can use a lite DOM implementation that is faster than jsdom.  (Jsdom implements lots of functionality that MathJax doesn't need, which accounts for the performance difference.)

I haven't done any formal testing between the two, but preliminary reports from others are that MathJax v3 is considerably faster.
