### ISSUE TITLE
How do I configure Mathjax?

### ISSUE THREAD

**Issue by Michael-Pascale** [mathjax/MathJax-demos-node#30]
How do I configure these options:
http://docs.mathjax.org/en/latest/options/document.html?highlight=Configuration#the-configuration-block
In the context of this demo:
https://github.com/mathjax/MathJax-demos-node/blob/master/direct/tex2chtml . 

Thanks,

**Comment by dpvc** [comment]
They go on line 93:

https://github.com/mathjax/MathJax-demos-node/blob/060220686e5e368d9b654169eb4199b1f3de5a96/direct/tex2chtml#L93

as options to the document being created.  Add them along side `InputJax` and `OutputJax`.

**Comment by Michael-Pascale** [comment]
as an example:
`{InputJax: tex, OutputJax: chtml, processHtmlClass: 'some-class'}`
or
`{ InputJax: tex, OutputJax: chtml, 
    options: {
        processHtmlClass: 'some-class'
    }
}`

Secondary question: would using this processHtmlClass option increase performance over going through the entire document?

**Comment by dpvc** [comment]
The first one.

**Comment by dpvc** [comment]
> would using this processHtmlClass option increase performance over going through the entire document?

Only slightly.  MathJax will look through the whole document anyway (looking for `ignoreHtmlClass` and `processHtmlClass`.

**Comment by Michael-Pascale** [comment]
Thanks! Those configurations work in that location!, and it did slightly improve performance, as you mentioned!
