### ISSUE TITLE
Can't run node tex2chtml-page demo with mathjax 3

### ISSUE THREAD

**Issue by fletcherdvalve** [mathjax/MathJax-demos-node#31]
First of all, if I can get this to work, it will be absolutely amazing for my 3D math for games book, which I produced in LaTeX but am working on converting to native web.  So I am a huge fan of this project and hope to be able to help you make it easier to use out of the box.

I cannot get the tex2chtml-page node demo to run.  Here's an example run.  Starting from an empty directory:

```
$ wget https://raw.githubusercontent.com/mathjax/MathJax-demos-node/master/simple/tex2chtml-page
(succeeds)
$ npm install esm yargs mathjax-full@3

added 23 packages, and audited 24 packages in 2s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ node -r esm tex2chtml-page --version
unknown
$ node -r esm tex2chtml-page ../web/cartesianspace.html
MathJax(?): Can't find handler for document
MathJax(?): Can't find handler for document
TypeError: Cannot read property 'startup' of undefined
    at /home/fletcherd/gamemath/mathjax/tex2chtml-page:95:29
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:63:3)
    at /home/fletcherd/gamemath/mathjax/node_modules/esm/esm.js:1:34535
    at /home/fletcherd/gamemath/mathjax/node_modules/esm/esm.js:1:34176
    at process.<anonymous> (/home/fletcherd/gamemath/mathjax/node_modules/esm/esm.js:1:34506)
    at Function.<anonymous> (/home/fletcherd/gamemath/mathjax/node_modules/esm/esm.js:1:296856)
    at Function.<anonymous> (/home/fletcherd/gamemath/mathjax/node_modules/esm/esm.js:1:296555)
    at Function.<anonymous> (/home/fletcherd/gamemath/mathjax/node_modules/esm/esm.js:1:284879)
    at Object.apply (/home/fletcherd/gamemath/mathjax/node_modules/esm/esm.js:1:199341)
```

Any idea what I might be doing wrong?

I'm using ubuntu bionic.  (Side note: bionic does not support "env -S", which is used in your shebangs.  Bionic is only 3 years old, and the only stable ubuntu release that supports the env -S syntax was released April of last year.)

**Comment by dpvc** [comment]
It is probably tied to the content of the page you are trying to process.  If MathJax can't parse the HTML (and it's LiteDOM is pretty simple), this is the message you will get.  Try a simple HTML page first, and see if that goes.  Follow your steps (on Mac OS) it works for me.  But I don't have your HTML file to test with.

**Comment by fletcherdvalve** [comment]
Ah.  It is indeed something particular to my html.  I will try to narrow down what LiteDOM doesn't like.

My next problem is that it isn't actually processing the math.  So I obviously have some really basic misunderstanding of how to tell mathjax what to do.


Input:
```
<html>
<body>
$x+y$
</body>
</html>
```

Output:

```
<!DOCTYPE html>
<html>
<head></head><body>
$x+y$
</body>
</html>
```

**Comment by dpvc** [comment]
Single-dollar-sign delimiters are not enabled by default, do you need to either use `\(...\)` or add more configuration to the `tex2chtml-page` command to enable single dollar signs.

**Comment by fletcherdvalve** [comment]
Great, that worked.  Thanks for the help!  My next issues will be ``align`` and related environments, and equation numbering.  Where can I find more about how to deal with those topics?

**Comment by dpvc** [comment]
The `align` environment is in the `ams` package, which is loaded automatically (see the `--packages` option), so that should work automatically.  Automatic equation numbers can be set using the `tex` block's `tags` option.  See the [tex input options](https://docs.mathjax.org/en/latest/options/input/tex.html) for more details.

**Comment by fletcherdvalve** [comment]
Thanks for your help.  I realize these are all questions I could have answered by Reading The Docs.  I tried!  I just didn't find what I was looking for.
