### ISSUE TITLE
Can I get the chtmlStyles css which contains all tex

### ISSUE THREAD

**Issue by niusibao** [mathjax/MathJax-demos-node#39]
I want to cache chtml in node server,but no css style.How I get the css file like mathjax-node that generate css.

**Comment by joshua7v** [comment]
I'm also facing the same issue.
After reading some documents about chtml output config,
It seems set `adaptiveCSS: false` will output all the css needed.

**Comment by niusibao** [comment]
> I'm also facing the same issue. After reading some documents about chtml output config, It seems set `adaptiveCSS: false` will output all the css needed.

It's right. Thanks!
