### ISSUE TITLE
'No version information available...' messages output when using simple/tex2chtml.js

### ISSUE THREAD

**Issue by rnwst** [mathjax/MathJax-demos-node#51]
When executing `simple/tex2chtml ''`, the output is
```
No version information available for component adaptors/liteDOM
No version information available for component adaptors/liteDOM
No version information available for component tex-chtml
No version information available for component tex-chtml
<mjx-container class="MathJax" jax="CHTML" display="true"><mjx-math display="true" style="margin-left: 0; margin-right: 0;" class=" MJX-TEX"></mjx-math></mjx-container>
```
When using the `component`, `preload`, or `direct` versions of `tex2chtml`, only the html is printed without the warnings.

**Version info:**
MathJax-demos-node@3.2.0
mathjax-full@3.2.2
Node.js v18.8.0

**Comment by dpvc** [comment]
Thanks, I can reproduce the issue and will look into it.

For now, these are just warnings, and you can ignore them for now.  They are printed to `stderr` not `stdout` so they won't be part of the captured output if you re redirecting to a file or piping to a program.

Alternatively, you can set

``` js
        versionWarnings: false
```

in the `loader` section of the MathJax configuration in `tex2chtml` to prevent the messages from being produced.

**Comment by rnwst** [comment]
Many thanks!
