### ISSUE TITLE
Many demos fail to run on Node version 21 with "Function.prototype.apply was called on undefined" errors

### ISSUE THREAD

**Issue by ddribin** [mathjax/MathJax-demos-node#59]
I am trying to use `component/tex2svg` and it fails with this error using Node `v21.6.2`. However it works with Node `v20.11.1`. I am on a macOS Sonoma 14.3 with both version of `node` installed via [Homebrew](https://brew.sh). Also note that the demos in `direct/` work on Node `v21.6.2`, but the ones in `component/` and `simple/` do not.

Here's the truncated error:

```
> /opt/homebrew/opt/node@21/bin/node -r esm ./tex2svg 'y = mx + b'
/Users/dave/src/MathJax-demos-node/node_modules/esm/esm.js:1
const __global__ = this; <... full-text-in-gist ... >


[/Users/dave/src/MathJax-demos-node/node_modules/cliui/build/index.cjs:1
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function]

Node.js v21.6.2
```

The full error is big, so I put it in a Gist:  https://gist.github.com/ddribin/8d1bf990f8edd87cdb14cf705b03b020

**Comment by ddribin** [comment]
Seems like this is maybe an issue with Node, itself. See:

- https://github.com/nodejs/node/issues/51081
- https://github.com/nodejs/node/pull/51356
- https://github.com/nodejs/node/pull/51390

**Comment by dpvc** [comment]
As you have determined, the issue is with the `esm`  library, which is no longer being developer or supported.  Fortunately, MathJax only needs it if you are running from the component source files.  So if you use

``` shell
/opt/homebrew/opt/node@21/bin/node tex2svg --dist 'y = mx + b'
```

that should work for you.

**Comment by dpvc** [comment]
PS, version 4 (now out in beta) does not have any dependency on `esm`, so in the future, this will not be a problem.

**Comment by ddribin** [comment]
Thanks for the response! Yes, `--dist` works, even with Node `v21.6.2`. And good news about v4.

**Comment by ddribin** [comment]
And thank you for MathJax! It is pretty great. ;-)

**Comment by dpvc** [comment]
Glad that worked, and thanks for the kind words!

**Comment by ddribin** [comment]
Quick followup here. Node `v21.7.0` was [just released](https://github.com/nodejs/node/releases/tag/v21.7.0) and it fixes the issue.

```
> node --version
v21.7.0
```

Gonna close this, since it is no longer an issue. Thanks for the help!

**Comment by dpvc** [comment]
Thanks for the additional information.  I ran into it in another situation myself, so glad to see that 21.7.0 resolves that.
